Vagrant.configure(2) do |config| 
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory=2048
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    # this should turn off the ubuntu console logs
    # http://vagrant.1086180.n5.nabble.com/what-is-cloudimg-console-log-td9969.html
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provision "shell", path: "./setup_assets/ubuntu_wp.sh"
  config.vm.provision "shell", run: "always" do |s|
    s.inline = "echo \"IP address for host file: \" && ifconfig enp0s8 | grep \"inet addr\" | awk '{ print $2 }' | sed -n -e 's/.*://p'"
  end
end