Vagrant.configure(2) do |config|
  # This is which box to use
  config.vm.box = "ubuntu/xenial64"
  # This is the type of private network
  config.vm.network "private_network", type: "dhcp"

  # lets give it a name that matches the folder name
  # This makes it so that we can store our meta data
  # anywhere by calling the machines folder something other than default
  config.vm.define File.basename(Dir.getwd)

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory=2048
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    # this should turn off the ubuntu console logs
    # http://vagrant.1086180.n5.nabble.com/what-is-cloudimg-console-log-td9969.html
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  # change this to true if you want to install php version 7.1.
  legacy = true
  if legacy
    config.vm.provision "shell", path: "./setup_assets/ubuntu_wp.sh", args: ['Y']
  else
    config.vm.provision "shell", path: "./setup_assets/ubuntu_wp.sh"
  end

  config.vm.provision "shell", run: "always" do |s|
    s.inline = "echo \"IP address for host file: \" && ifconfig enp0s8 | grep \"inet addr\" | awk '{ print $2 }' | sed -n -e 's/.*://p'"
  end
end
