Vagrant.configure(2) do |config|
  # This is which box to use
  config.vm.box = "VAGRANT_BOX"

  # lets give it a name that matches the folder name
  # This makes it so that we can store our meta data
  # anywhere by calling the machines folder something other than default
  config.vm.define File.basename(File.dirname(__FILE__))

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory=2048
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    # this should turn off the ubuntu console logs
    # http://vagrant.1086180.n5.nabble.com/what-is-cloudimg-console-log-td9969.html
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  # change this to true if you want to install php version 7.1.
  version = "PHP_VERSION"
  if version == "latest"
    config.vm.provision "shell", path: "./setup_assets/provisioner.sh"
  else
    config.vm.provision "shell", path: "./setup_assets/provisioner.sh", args: [version]
  end

  # Option to create a forward port network
  # or a private network. we want to always land on
  # forwarded port unless private is explicitly set.
  networkType = "NETWORK_TYPE"
  if networkType == "private"
    config.vm.network "private_network", type: "dhcp"
    # If we are using a private network - lets have it tell us what the ip is when its launched
    config.vm.provision "shell", run: "always" do |s|
      s.inline = "echo \"IP address for host file: \" && ifconfig enp0s8 | grep \"inet addr\" | awk '{ print $2 }' | sed -n -e 's/.*://p'"
    end
  else
    config.vm.network "forwarded_port", guest: FORWARD_GUEST_PORT, host: FORWARD_HOST_PORT
  end

  # noticed some strange behavior with apache
  # so at the start and stop of all boxes lets restart apache
  config.vm.provision "shell", run: "always" do |s|
    s.inline = "service apache2 stop"
    s.inline = "service apache2 start"
  end

end
